name: Run Workflow Builder Evals

on:
  push:
    branches:
      - master
      - ai-1492-feature-set-up-running-evaluations-in-ci
    paths:
      - 'packages/@n8n/ai-workflow-builder.ee/**'
      - '.github/workflows/ci-evals.yml'
  pull_request:
    paths:
      - 'packages/@n8n/ai-workflow-builder.ee/**'
      - '.github/workflows/ci-evals.yml'

jobs:
  evals:
    name: Run Evaluations
    runs-on: ubuntu-latest
    env:
      N8N_AI_ANTHROPIC_KEY: ${{ secrets.EVALS_ANTHROPIC_KEY }}
      LANGSMITH_TRACING: true
      LANGSMITH_ENDPOINT: ${{ secrets.EVALS_LANGSMITH_ENDPOINT }}
      LANGSMITH_API_KEY: ${{ secrets.EVALS_LANGSMITH_API_KEY }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup and Build
        uses: ./.github/actions/setup-nodejs-github

      - name: Run Evaluations
        working-directory: packages/@n8n/ai-workflow-builder.ee/evaluations
        run: |
          pnpm eval:langsmith
